package com.goglitter.domain.request

/*data class AddressDetailsItem(
	val locality: String? = null,
	val village: String? = null,
	val landmark: String? = null,
	val latitude: String? = null,
	val city: String? = null,
	val longitude: String? = null,
	val addressLine3: String? = null,
	val addressLine2: String? = null,
	val addressLine1: String? = null,
	val state: String? = null,
	val addressLine4: String? = null,
	val country: String? = null,
	val addressType: String? = null,
	val district: String? = null,
	val pincode: String? = null
)

data class LeadDetails(
	val timeSpentonPage: String? = null,
	val onlineCoversionSR: String? = null,
	val referredByOtherEmail: String? = null,
	val officePhone: String? = null,
	val uTMLeadPropensity: String? = null,
	val successorfailurestatusonfinalpageofjourney: String? = null,
	val product: String? = null,
	val branchSolId: String? = null,
	val partnerId: String? = null,
	val timeOfLeadDrop: String? = null,
	val leadType: String? = null,
	val gender: String? = null,
	val affluentCustomer: Boolean? = null,
	val pAOffer: String? = null,
	val uCIC: String? = null,
	val fedIDoftheCustomer: String? = null,
	val remarks: String? = null,
	val modeOfCommunication: String? = null,
	val firstTimePAOfferFlag: String? = null,
	val referrerUCIC: String? = null,
	val uTMCampaign: String? = null,
	val dateOfBirth: String? = null,
	val cVCESegment: String? = null,
	val uTMGAID: String? = null,
	val productSubType: String? = null,
	val priority: String? = null,
	val preferredCallStartTime: String? = null,
	val leadNumber: String? = null,
	val assignmentBasedOn: String? = null,
	val bREResponse: String? = null,
	val referrerOrganizationName: String? = null,
	val preferredCallEndTime: String? = null,
	val destCode: String? = null,
	val customerId: String? = null,
	val customerType: String? = null,
	val emailAddress: String? = null,
	val preferredCallTime: String? = null,
	val uTMNTBID: String? = null,
	val overseascountry: String? = null,
	val referrerCustomerId: String? = null,
	val leadSource: String? = null,
	val medium: String? = null,
	val referredByOtherName: String? = null,
	val referredByChannelPartnerId: String? = null,
	val lastName: String? = null,
	val uTMLeadPriority: String? = null,
	val timezone: String? = null,
	val referrerEmployeeId: String? = null,
	val referrerAccountNumber: String? = null,
	val uTMGCIID: String? = null,
	val referralType: String? = null,
	val referredByOtherPhone: String? = null,
	val campaignName: String? = null,
	val salutation: String? = null,
	val uTMLeadScore: String? = null,
	val leadStatus: String? = null,
	val referredByLeadId: String? = null,
	val serviceFlag: String? = null,
	val pANNumber: String? = null,
	val leadGenerator: String? = null,
	val assignmentId: String? = null,
	val dropoffPageNumber: String? = null,
	val countryCode: String? = null,
	val residencyStatus: String? = null,
	val uTMFEDID: String? = null,
	val parentLeadNumber: String? = null,
	val pincodeLead: String? = null,
	val leadChannel: String? = null,
	val referrerPanNumber: String? = null,
	val customerSegment: String? = null,
	val individualOrganizationName: String? = null,
	val pPACode: String? = null,
	val firstName: String? = null,
	val employeeIDandSOLIDwhoassistedthecustomer: String? = null,
	val uotmCode: String? = null,
	val residencePhone: String? = null,
	val sMSShortCode: String? = null,
	val uTMLms: String? = null,
	val middleName: String? = null,
	val accountType: String? = null,
	val assignedToSelf: String? = null,
	val nationality: String? = null,
	val alternateContactNumber: String? = null,
	val accountNumber: String? = null,
	val mobileNumber: String? = null,
	val uTMInfo: String? = null,
	val assignmentType: String? = null,
	val referrerMobileNumber: String? = null,
	val aggregatorLeadSource: String? = null,
	val dropOffPageName: String? = null,
	val uTMITM: String? = null,
	val referrerUCC: String? = null
)

data class GoldLoanRequest(
	val motherMaidenName: String? = null,
	val grossAnnualIncome: String? = null,
	val instanceId: String? = null,
	val loanTenure: String? = null,
	val religion: String? = null,
	val sourceOfFunds: String? = null,
	val gender: String? = null,
	val variantFacilityType: String? = null,
	val rOI: String? = null,
	val disbursalDate: String? = null,
	val vernacularDeclaration: String? = null,
	val transactionId: String? = null,
	val loanAmount: String? = null,
	val loanAccountNumber: String? = null,
	val applicantIdCustId: String? = null,
	val subAgentCode: String? = null,
	val loanAmountDisbursed: String? = null,
	val maritalStatus: String? = null,
	val education: String? = null,
	val assessmentId: String? = null,
	val personWithDisability: String? = null,
	val fatherName: String? = null
)

data class OrganisationDetails(
	val mobileNo: String? = null,
	val contactPersonPanNumber: String? = null,
	val contactPersonMiddleName: String? = null,
	val ppaCode: String? = null,
	val contactPersonUCIC: String? = null,
	val contactPersonMobileNumber: String? = null,
	val contactPersonFirstName: String? = null,
	val emailAddress: String? = null,
	val accountNumber: String? = null,
	val companyName: String? = null,
	val uCC: String? = null,
	val panNumber: String? = null,
	val dateOfIncorporation: String? = null,
	val contactPersonLastName: String? = null
)

data class AppointmentDetails(
	val isJointActivity: String? = null,
	val purposeOfMeeting: String? = null,
	val startDateTime: String? = null,
	val initiatedBy: String? = null,
	val placeOfMeeting: String? = null,
	val appointmentStatus: String? = null,
	val engagementType: String? = null
)

data class CrmRequest(
	val leadDetails: LeadDetails? = null,
	val addressDetails: List<AddressDetailsItem?>? = null,
	val callBackUrl: String? = null,
	val organisationDetails: OrganisationDetails? = null,
	val leadType: String? = null,
	val isAsync: Boolean? = null,
	val appointmentDetails: AppointmentDetails? = null,
	val applicationDetails: ApplicationDetails? = null
)

data class ApplicationDetails(
	val goldLoanRequest: GoldLoanRequest? = null
)*/


data class CrmRequest(
	val fname: String? = null,
	val lname: String? = null,
	val number: String? = null,
	val pincode: String? = null,
	val email: String? = null
)

